services:
  ollama:
    # amd gpu
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    devices:
      - "/dev/kfd"
      - "/dev/dri"

volumes:
  ollama_data:
    name: ollama_data